name: logzilla
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.2.1+1
  colorize: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0